# Generated by Django 4.2.30 on 2026-07-28 07:06
# biplane: schema for WorkflowTemplate + seed of the five built-in system templates,
# so a named workflow is versioned in code and can't vanish with a lost volume.

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


# (name, group, color) per state; sequence assigned in order, first backlog = default.
SYSTEM_TEMPLATES = [
    {
        "name": "Plane Default",
        "description": "The standard Plane workflow.",
        "states": [
            ("Backlog", "backlog", "#60646C"),
            ("Todo", "unstarted", "#60646C"),
            ("In Progress", "started", "#F59E0B"),
            ("Done", "completed", "#46A758"),
            ("Cancelled", "cancelled", "#9AA4BC"),
            ("Triage", "triage", "#4E5355"),
        ],
    },
    {
        "name": "Biplane",
        "description": "Biplane's build pipeline: design → code → review → integrate → deploy.",
        "states": [
            ("Backlog", "backlog", "#60646C"),
            ("Todo", "unstarted", "#60646C"),
            ("Design", "started", "#8b5cf6"),
            ("Code & TDD", "started", "#3b82f6"),
            ("Review", "started", "#ec4899"),
            ("Integration Test", "started", "#f59e0b"),
            ("Deploy", "completed", "#10b981"),
            ("Done", "completed", "#46A758"),
            ("Cancelled", "cancelled", "#9AA4BC"),
            ("Triage", "triage", "#4E5355"),
        ],
    },
    {
        "name": "Scrum",
        "description": "Sprint-based flow with a review stage.",
        "states": [
            ("Product Backlog", "backlog", "#60646C"),
            ("Sprint Backlog", "unstarted", "#60646C"),
            ("In Progress", "started", "#F59E0B"),
            ("In Review", "started", "#ec4899"),
            ("Done", "completed", "#46A758"),
            ("Cancelled", "cancelled", "#9AA4BC"),
            ("Triage", "triage", "#4E5355"),
        ],
    },
    {
        "name": "Kanban",
        "description": "Continuous flow with a blocked lane.",
        "states": [
            ("Backlog", "backlog", "#60646C"),
            ("To Do", "unstarted", "#60646C"),
            ("In Progress", "started", "#F59E0B"),
            ("Blocked", "started", "#ef4444"),
            ("Review", "started", "#ec4899"),
            ("Done", "completed", "#46A758"),
            ("Cancelled", "cancelled", "#9AA4BC"),
            ("Triage", "triage", "#4E5355"),
        ],
    },
    {
        "name": "Bug Triage",
        "description": "Defect lifecycle from report to resolution.",
        "states": [
            ("New", "backlog", "#60646C"),
            ("Triage", "triage", "#4E5355"),
            ("Confirmed", "unstarted", "#60646C"),
            ("In Progress", "started", "#F59E0B"),
            ("In Review", "started", "#ec4899"),
            ("Resolved", "completed", "#46A758"),
            ("Closed", "completed", "#10b981"),
            ("Won't Fix", "cancelled", "#9AA4BC"),
        ],
    },
]


def seed_system_templates(apps, schema_editor):
    WorkflowTemplate = apps.get_model("db", "WorkflowTemplate")
    for tmpl in SYSTEM_TEMPLATES:
        states = []
        for i, (name, group, color) in enumerate(tmpl["states"]):
            entry = {"name": name, "group": group, "color": color, "sequence": (i + 1) * 15000}
            if group == "backlog" and not any(s.get("default") for s in states):
                entry["default"] = True
            states.append(entry)
        WorkflowTemplate.objects.update_or_create(
            name=tmpl["name"],
            workspace=None,
            is_system=True,
            defaults={"description": tmpl["description"], "states": states},
        )


def remove_system_templates(apps, schema_editor):
    WorkflowTemplate = apps.get_model("db", "WorkflowTemplate")
    WorkflowTemplate.objects.filter(is_system=True, workspace=None).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0122_profile_time_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_system', models.BooleanField(default=False)),
                ('states', models.JSONField(default=list)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(blank=True, help_text='Null for system/built-in templates shared across the instance.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_templates', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Workflow Template',
                'verbose_name_plural': 'Workflow Templates',
                'db_table': 'workflow_templates',
                'ordering': ('-is_system', 'name'),
            },
        ),
        migrations.RunPython(seed_system_templates, remove_system_templates),
    ]
