# Generated by Django 4.2.30 on 2026-07-31 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0124_biplane_template_done_before_deploy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgejoDelivery',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('delivery_id', models.CharField(max_length=128, unique=True)),
                ('event', models.CharField(max_length=32)),
                ('payload', models.JSONField()),
                ('repository', models.CharField(max_length=512)),
                ('body_digest', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('processed', 'processed')], default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('lease_token', models.CharField(blank=True, max_length=64, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Forgejo Delivery',
                'verbose_name_plural': 'Forgejo Deliveries',
                'db_table': 'forgejo_deliveries',
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='forgejo_del_status_bbcf02_idx'), models.Index(fields=['status', 'lease_expires_at'], name='forgejo_del_status_0bdc15_idx')],
            },
        ),
    ]
