# Generated by Django 4.2.30 on 2026-08-16 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0130_poll_cursor"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardOperation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("principal", models.CharField(max_length=255)),
                ("op_key", models.CharField(max_length=255)),
                ("source", models.CharField(max_length=64)),
                ("request_digest", models.CharField(max_length=64)),
                ("verb", models.CharField(max_length=64)),
                ("workspace_slug", models.CharField(max_length=255)),
                ("project_identifier", models.CharField(blank=True, max_length=255)),
                ("outcome", models.JSONField(default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Board Operation",
                "verbose_name_plural": "Board Operations",
                "db_table": "board_operations",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddConstraint(
            model_name="boardoperation",
            constraint=models.UniqueConstraint(
                fields=("principal", "op_key"), name="board_operation_principal_op_key_uniq"
            ),
        ),
    ]
