# Copyright (c) 2026 The Biplane Authors
# SPDX-License-Identifier: AGPL-3.0-only
# See the LICENSE file for details.

"""Renderer conformance: the parser measured against the deployed forge (BIP-45).

The corpus in ``renderer_corpus.json`` is generated by ``render_corpus_gen.py``
against a live Forgejo and committed. **This module is offline** — a live forge
is not a test dependency, and a corpus that re-derived itself at test time
would be an input choosing its own validation (invariant 7).

Each candidate line carries TWO independent facts from the renderer, and the
whole design of this module is that they are not the same question:

``visible``
    Can a human see this line at all, in any container? This is the SAFETY
    floor (Vex 3354). A line nobody can see must never act — that is
    unauthorized completion, and no policy may pin it away. Enforced by
    :func:`test_never_fires_on_text_no_human_can_see`.

``in_prose``
    Does the renderer place the line in a top-level paragraph? This is the
    POSITIVE rule. A directive there that we ignore is silent inertness, the
    BIP-33 failure class, enforced by
    :func:`test_never_silently_ignores_top_level_prose`.

Everything between them — visible, but rendered inside something that is not a
top-level paragraph — is POLICY, and policy has to be *named* to exist. Those
cases live in ``POLICY`` below with the ruling that decided each one, so no
behaviour can drift in on the quiet: an unnamed case fails.

Out of scope here on purpose, still hand-pinned in ``test_completion_grammar``:
start-of-line anchoring, near-miss loudness, the comment-coexistence rule,
duplicate collapse and conflict demotion. An oracle carrying our own policy
would simply ratify our choices back to us.
"""

from __future__ import annotations

import json
import pathlib

import pytest

from plane.bridge.grammar import parse_directives

_CORPUS_PATH = pathlib.Path(__file__).with_name("renderer_corpus.json")

with _CORPUS_PATH.open(encoding="utf-8") as _fh:
    CASES = json.load(_fh)["cases"]

# ---------------------------------------------------------------------------
# POLICY: visible to a human, but NOT in a top-level paragraph.
#
# Value is the set of source lines that must fire. Every entry cites the ruling
# that put it here. Adding a case to this table is a deliberate act with a
# named reason; a visible non-prose case that is absent fails the suite rather
# than quietly inheriting whatever the parser happens to do.
# ---------------------------------------------------------------------------
POLICY: dict[str, set[int]] = {
    # -- FIRE ---------------------------------------------------------------
    # Vex 3354 condition 9: a badge or <details> at the top of a PR body folds
    # the trailer under it into one html_block. Forgejo renders BOTH, so
    # dropping these lines would be silent inertness dressed as tidiness.
    "html-img-badge-then-trailer": {2},
    "html-details-then-trailer": {3},
    # Vex 3354 ruling: Forgejo renders `Closes BIP-7` above `: why` as a
    # VISIBLE <dt>. Firing is an over-fire in the SAFE direction — a human can
    # read it and object. Chasing Goldmark's extension set to suppress it
    # measurably made things worse (the deflist plugin turned this correct
    # fire into a silent miss).
    "deflist": {1},
    "deflist-empty-body": {1},
    "deflist-then-real": {1, 4},
    "deflist-visible-dt": {1},
    # -- SUPPRESS -----------------------------------------------------------
    # Fenced code is the archetype of the grey zone, and it is why visibility
    # cannot be the positive rule: a human plainly SEES `Closes BIP-7` inside
    # a ``` block, and it must still never fire. Code is a demonstration of a
    # directive, not the making of one — which is most of what our own docs
    # and PR bodies do with this grammar. Morrow 3333 established the fence
    # pairing rules; every variant is pinned because each one was a way of
    # closing parser state while the rendered Markdown stayed fenced.
    "fence-backtick": set(),
    "fence-tilde": set(),
    "fence-info-string": set(),
    "fence-unclosed": set(),
    "fence-short-closer": set(),
    "fence-mismatched-char": set(),
    "fence-indented-opener": set(),
    # Quoted text is someone else's words; a trailer inside a quote is a
    # report of a directive, not the making of one (Morrow 3333/3334).
    "quote-lazy-continuation": set(),
    "autolink-in-quote-para": set(),
    # List items and their lazy continuations are bullet content, not
    # trailers. NOTE: this is the live disagreement raised with Vex — his
    # visibility invariant, taken as the positive rule rather than a floor,
    # would make these fire, and `- Closes BIP-7` in a checklist with it.
    "list-lazy-continuation": set(),
    "quote-then-list-lazy": set(),
    # Morrow 10808: a no-blank trailer above `---`/`===` is HEADING context —
    # zero directives and zero near-misses. The blank-line control still
    # completes, and is asserted as prose above, not here.
    "setext-h1": set(),
    "setext-h2": set(),
    "setext-h2-long": set(),
    "setext-then-real": set(),
}


def _candidates(case):
    return case["expected"]


def test_container_tokens_are_never_emitted_at_top_level():
    """Pin the UPSTREAM behaviour the container rule depends on (Vex 3358).

    ``_CLASSIFIABLE`` is filtered by ``level == 0``, and the claim that adding
    ``list_item_open`` to it would be inert rests on markdown-it never
    emitting that token at top level — the outer ``bullet_list_open`` holds
    level 0 instead. That is a property of the tokenizer, not of our code, so
    a version upgrade could change it silently and turn an equivalent mutant
    into a live hole. Assert it rather than leave it as folklore.
    """
    from plane.bridge.grammar import _MD

    samples = [
        "- item\nCloses BIP-7\n",
        "1. item\nCloses BIP-7\n",
        "> quoted\nCloses BIP-7\n",
        "| a |\n| - |\n| Closes BIP-7 |\n",
    ]
    # ONLY the tokens that carry content lines INSIDE a container. The outer
    # container openers — bullet_list_open, blockquote_open, table_open — are
    # themselves at level 0, which is exactly why `_CLASSIFIABLE` has to be a
    # whitelist of content blocks rather than a blacklist of containers. A
    # first draft of this test asserted blockquote_open was nested and failed
    # immediately; the correction is the point worth keeping.
    content_carriers = {"list_item_open", "td_open", "th_open", "tr_open"}
    for markdown in samples:
        for token in _MD.parse(markdown):
            if token.type in content_carriers:
                assert token.level > 0, (
                    f"{token.type} appeared at level 0 for {markdown!r}; the "
                    f"container rule's top-level filter no longer holds"
                )


def test_accepted_over_fires_stay_an_enumerated_set():
    """Vex 3355: an over-fire is DISCOVERABLE, not harmless — it closes a
    ticket that isn't done, and what makes it acceptable is only that the
    causing text is on screen and attributable. So the accepted set is
    counted, not an open category. Left as a category, "safe direction"
    becomes the standing justification for the next admission and nobody ever
    has to argue for entry. Growth here means the container rule is drifting
    from the renderer, and the growth is the signal."""
    firing = {name for name, lines in POLICY.items() if lines}
    assert firing == {
        "deflist",
        "deflist-empty-body",
        "deflist-then-real",
        "deflist-visible-dt",
        "html-img-badge-then-trailer",
        "html-details-then-trailer",
    }, (
        "the accepted over-fire set changed. That is an admission decision: "
        "cite the ruling that admitted it, or fix the parser instead."
    )


def test_corpus_is_present_and_covers_both_directions():
    """A silently empty or one-sided corpus makes every case below vacuous."""
    assert len(CASES) >= 70, f"corpus shrank to {len(CASES)} cases"
    cands = [c for case in CASES for c in _candidates(case)]
    assert any(c["in_prose"] for c in cands), "no positive prose case"
    assert any(not c["visible"] for c in cands), "no invisible-text case"
    assert any(
        c["visible"] and not c["in_prose"] for c in cands
    ), "no visible-but-not-prose case — the policy boundary is untested"


@pytest.mark.parametrize("case", CASES, ids=[c["name"] for c in CASES])
def test_never_fires_on_text_no_human_can_see(case):
    """THE SAFETY FLOOR. No policy may pin an exception into this.

    A directive on a line the forge renders to nothing is a ticket
    completion no reviewer could have seen — attacker-controlled, invisible,
    unauthorized (Vex 3354).
    """
    fired = set(parse_directives(case["markdown"], "pr_body").recognized_lines)
    invisible = {c["line"] for c in _candidates(case) if not c["visible"]}

    assert not (fired & invisible), (
        f"{case['name']}: fired on line(s) {sorted(fired & invisible)} that "
        f"render to NOTHING on the forge.\n"
        f"--- markdown ---\n{case['markdown']}\n"
        f"--- rendered ---\n{case['html']}"
    )


@pytest.mark.parametrize("case", CASES, ids=[c["name"] for c in CASES])
def test_never_silently_ignores_top_level_prose(case):
    """BIP-33: a directive the renderer puts in plain prose must not be inert."""
    fired = set(parse_directives(case["markdown"], "pr_body").recognized_lines)
    prose = {c["line"] for c in _candidates(case) if c["in_prose"]}

    assert prose <= fired, (
        f"{case['name']}: line(s) {sorted(prose - fired)} render as top-level "
        f"prose and were silently ignored.\n"
        f"--- markdown ---\n{case['markdown']}\n"
        f"--- rendered ---\n{case['html']}"
    )


@pytest.mark.parametrize("case", CASES, ids=[c["name"] for c in CASES])
def test_visible_non_prose_behaviour_is_named_policy(case):
    """Everything between the floor and the positive rule must be a RULING."""
    grey = {c["line"] for c in _candidates(case) if c["visible"] and not c["in_prose"]}
    if not grey:
        return

    assert case["name"] in POLICY, (
        f"{case['name']} renders line(s) {sorted(grey)} as VISIBLE text "
        f"outside a top-level paragraph. That is a policy call and it has no "
        f"entry in POLICY — decide it and cite the ruling, do not let the "
        f"parser's current behaviour become the answer by default.\n"
        f"--- rendered ---\n{case['html']}"
    )

    fired = set(parse_directives(case["markdown"], "pr_body").recognized_lines)
    assert fired & grey == POLICY[case["name"]] & grey, (
        f"{case['name']}: policy says lines {sorted(POLICY[case['name']] & grey)} "
        f"fire, parser fired {sorted(fired & grey)}."
    )


@pytest.mark.parametrize("case", CASES, ids=[c["name"] for c in CASES])
def test_class_and_key_agree_where_both_fire(case):
    """Where both agree a line is live, they must agree on WHAT it says."""
    result = parse_directives(case["markdown"], "pr_body")
    by_line = {d.line: (d.keyword_class, d.ticket_key) for d in result.directives}

    for cand in _candidates(case):
        if cand["line"] not in by_line:
            continue  # collapsed by duplicate policy, checked by hand
        if cand["key"] in result.conflicts:
            # Demotion deliberately REWRITES the class at the first line, so
            # parser and corpus must disagree here. That disagreement is the
            # policy working; it is pinned by hand, not by the oracle.
            continue
        assert by_line[cand["line"]] == (cand["class"], cand["key"]), (
            f"{case['name']} line {cand['line']}: parser says "
            f"{by_line[cand['line']]}, corpus says {(cand['class'], cand['key'])}"
        )
