FROM node:22-alpine@sha256:c610fcdfb1d5b4740dd70c284ed3cb16bb857e0f7166196e36a5501df7a3aa32
RUN apk add --no-cache libc6-compat
# Set working directory
WORKDIR /app

COPY . .

RUN corepack enable pnpm && pnpm add -g turbo
RUN pnpm install

ENV VITE_ADMIN_BASE_PATH="/admin"

EXPOSE 3000

VOLUME [ "/app/node_modules", "/app/admin/node_modules" ]

CMD ["pnpm", "dev", "--filter=admin"]
